/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/coffee_bean.glb 
Author: Digital Archive of Natural History (DiNArDa) (https://sketchfab.com/disc3d)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/coffee-bean-9cae5abb7c2e4e57a405579fa6922672
Title: Coffee bean
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coffee_bean.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Coffee_DM_01_01} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Coffee_DM_01_01} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Coffee_DM_01_01} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Coffee_DM_01_01} />
      </group>
    </group>
  )
}

useGLTF.preload('/coffee_bean.glb')
