/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/coffee1.glb 
Author: Ephrem_art_ (https://sketchfab.com/ephrem_art_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-beans-3d-model-cc0c5ddb80ac472dbcae63a22db877f4
Title: Coffee Beans 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/coffee1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.coffee_bean} rotation={[Math.PI / 2, 0, 0]} scale={0.045} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/coffee1.glb')
