/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/stylized_eye.glb 
Author: merrychuu (https://sketchfab.com/merrynguyen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-eye-4fed6c71faca4932926c70a9385a7cee
Title: Stylized Eye
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Coffee(props) {
  const { nodes, materials } = useGLTF('./models/stylized_eye.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, 1.507]}>
        <mesh geometry={nodes.polySurface1_Pupil_0.geometry} material={materials.Pupil} />
        <mesh geometry={nodes.polySurface2_Eye_0.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/stylized_eye.glb')
