/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/lowpoly_coffee_mug.glb 
Author: Miichelle mansour (https://sketchfab.com/miichellemansour)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-coffee-mug-242ad92f3bff4a11bc15029aff27ba1d
Title: Lowpoly Coffee Mug
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mug(props) {
  const { nodes, materials } = useGLTF('./models/lowpoly_coffee_mug.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.571, 0.005, 0.6]} scale={0.6}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/lowpoly_coffee_mug.glb')
